### ISSUE TITLE
Need files/modules of Brain_19 & Brain19_5

### ISSUE THREAD

**Issue by Shantan243** [Cernewein/multi-building-RL#1]
Hello Author,
Greetings!

             I was going through the code and in environment.py module, i have found two directories links for Brain_19 and Brain19_5, whose files are not existed in the Repo. Could you please help share the same.

For easy ref: I looking for -

data/environment/heating-RL-agentDDPG-1h-19_more_responsive.pt
data/environment/heating-RL-agentDDPG-1h-19.5_more_responsive.pt

**Comment by Cernewein** [comment]
Hi,

These files (model weights) are too big for easy upload onto github. These are the result of training the DDPG agent contained in the related repo https://github.com/Cernewein/heating-RL-agent. You can use the code in there to train DDPG agents controlling the houses, which can then be used in this project.
Hope this helps !

**Comment by Shantan243** [comment]
Hi,
    As per above inputs, i have tried loading and running Heating-RL repo. We have succueesfully evaluated but did not get below models.


1. heating-RL-agentDDPG-1h-19.5_more_responsive.pt
2. heating-RL-agentDDPG-1h-19_more_responsive.pt

Request to share the link along with the access for the models or Please upload on Onedrive/Google drive and share the link with access to download and view.
